---
version: '3.8'
services:
    nexus:
      image: "sonatype/nexus3:latest"
      ports:
          - "8081:8081"
          - "8082:8082"
          - "8083:8083"
      volumes:
          - type: bind
            source: /srv/nexus
            target: /nexus-data
    gitlab:
      hostname: gitlab.6ax.su
      image: "gitlab/gitlab-ee:latest"
      ports:
          - "80:80"
          - "443:443"
          - "2222:22"
      volumes:
          - type: bind
            source: /srv/gitlab/config
            target: /etc/gitlab
          - type: bind
            source: /srv/gitlab/logs
            target: /var/log/gitlab
          - type: bind
            source: /srv/gitlab/data
            target: /var/opt/gitlab
    jenkins:
      image: jenkins/jenkins:lts
      ports:
          - "8080:8080"
          - "50000:50000"
      volumes:
          - type: bind
            source: /srv/jenkins
            target: /var/jenkins_home
